/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package yoMamaBot2;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        YoMama classUnderTest = new YoMama();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
