/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package yoMamaBot2;

public class YoMama {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new YoMama().getGreeting());
    }
}
